---
name: Testing

on:
  pull_request:
  push:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update APT index
        run: sudo apt-get update

      - name: Install DEB packages
        run: sudo apt-get install emacs-nox git --yes

      - name: Run Emacs
        run: emacs --debug-init
